environment:
  matrix:
    - nodejs_version: "4"
    - nodejs_version: "6"

install:
  # install npm modules.
  - yarn install --ignore-engines

# Post-install test scripts.
test_script:
  # run tests
  - npm test

# Don't actually build.
build: off
